
export default {
    WMS_TERMINALS: 'WMS_TERMINALS',

    // Terminal Events
    WMS_TERMINAL_DATA_UPDATED: 'WMS_TERMINAL_DATA_UPDATED',
    WMS_TERMINAL_STATE_UPDATED: 'WMS_TERMINAL_STATE_UPDATED',
    WMS_TERMINAL_DATA: 'WMS_TERMINAL_DATA',
    WMS_TERMINAL_STATE: 'WMS_TERMINAL_STATE',
    WMS_TERMINALS_METERING_REQ: 'WMS_TERMINALS_METERING_REQ',
    WMS_TERMINALS_METERING: 'WMS_TERMINALS_METERING',
    WMS_TERMINALS_METERING_UPDATE: 'WMS_TERMINALS_METERING_UPDATE',

    // Tank Events
    WMS_TANK_PUMP_STATE: 'WMS_TANK_PUMP_STATE',
    WMS_TANK_PUMP_STATE_UPDATED: 'WMS_TANK_PUMP_STATE_UPDATED',
    WMS_TANK_WATER_LEVEL: 'WMS_TANK_WATER_LEVEL',
    WMS_TANK_WATER_LEVEL_UPDATED: 'WMS_TANK_WATER_LEVEL_UPDATED',

    // Billing Events
    WMS_TERMINAL_BILLING: 'WMS_TERMINAL_BILLING',
    WMS_TERMINAL_BILLING_UPDATED: 'WMS_TERMINAL_BILLING_UPDATED',
    WMS_CURRENT_BILLS: 'WMS_CURRENT_BILLS',
    WMS_CURRENT_BILLS_REQ: 'WMS_CURRENT_BILLS_REQ'
};
